### ISSUE TITLE
Один ключ на несколько доменов

### ISSUE THREAD

**Issue by pafnuty** [Mofsy/pcp-cs#15]
Не знаю насколько реально, но было бы неплохо реализовать возможность одного ключа на несколько доменов.
Т.е. в параметрах ключа есть циферка, отвечающая за максимальное количество доменов (без учёта или с учётом настроек использования на поддоменах и доменных зонах), на которых может быть активирован скрипт.

**Comment by pafnuty** [comment]
Если реализовать - то можно вводить дополнительные скидки для оптовиков )) 
К примеру клиент имеет неопределённое количество сайтов и получается так, что для каждого сайта мне нужно генерить отдельный ключ по запросу, но гарантии, что это действительно его сайты - нет, и получается, что он сможет барыжить модулем, а так я дал ему ключ на 10 доменов со скидкой и все рады)

**Comment by pafnuty** [comment]
А ещё лучше применение:
- если указать 0 - ключ будет действовать на неограниченное кол-во сайтов. Таким образом можно делать демо-версии продукта.

**Comment by Mofsy** [comment]
@pafnuty Хм... Тогда в чем смысл привязывания?

**Comment by pafnuty** [comment]
Ок, пусть пока будет возможность проверки только ip сервера - если доменов много - пусть держат на одном серваке))

**Comment by D0Gmatist** [comment]
1) с генерированный ключ
2) количество доменов
3) список доменов (оно же и количество)

человек устанавливает модуль, вводит ключ лицензии, на сервер отправляется ключ и проходит проверку, если ключ ещё активен, заносим домен в копилку ключа
