### ISSUE TITLE
Local network

### ISSUE THREAD

**Issue by korzhyk** [Mofsy/pcp-cs#16]
How use this "module" with a front-end balancer and back-end app servers which didn't have an internet connection?

**Comment by Mofsy** [comment]
Не обязательно на английском.
Тут есть два варианта,
1. Нужно поднять окружение для сервера лицензий в пределах локальной сети.
2. Просто выдавать локальный ключ в ручном режиме с неограниченным сроком действия (never). Скрипт будет его проверять без запросов на сервер. Но в таком случае, аннулирование лицензии невозможно.
