### ISSUE TITLE
Ошибка: локальный ключ не подходит к данному окружению

### ISSUE THREAD

**Issue by locksmith77** [Mofsy/pcp-cs#17]
У меня выдало ошибку при активации ключа (локально) а сервер PCP стоит внешний вот такую:
Ошибка: локальный ключ не подходит к данному окружению. 
А в админке пишет, что лицензия активна и правильно показывает домен. Также при указании параметра $protect->use_localhost = true; все равно выдает ту же ошибку. Также в папке data появляется полноценный showattach.lic. В методах на сервере ни к чему не привязан. Подскажите в чем проблема?

**Comment by Mofsy** [comment]
@locksmith77 скорее всего не правильно указан секретный ключ...

**Comment by pafnuty** [comment]
@locksmith77 проверьте соответсвие секретного ключа на клиенте и в методе проверки.

**Comment by locksmith77** [comment]
Сменил в методе. Сменил на клиента. Выставил повторную активацию. Удалил файл лицензии. Активация прошла нормально. Ошибка осталась та же. А секретный ключ там как фильтруется? может он не нравится. Делал такой: ilqkdfg2hjcq3o5wi4q7

**Comment by locksmith77** [comment]
Попробовал простейший ключ: 123456. Все тоже самое.

**Comment by locksmith77** [comment]
Попробовал указать в методе проверять домен. Все заработало! Чем это чревато на локальном хосте? и будет ли работать все это если ключи будут у всех одинаковые для теста?

**Comment by locksmith77** [comment]
Также возник важный вопрос! (уже задавал но не пробовал). Как сделать один ключ на всех? я попробовал активировать локально с другого сайта тот же ключ. Приходится выставлять повторную активацию.Если скопировать файл ключа showattach.lic то выходит ошибка: локальный ключ не подходит к данному окружению.

**Comment by locksmith77** [comment]
Если в методе выставить по имени пользователя user_name, то что это за имя? то что прописано по желанию в лицензии при создании? или что-то другое?

**Comment by Mofsy** [comment]
@locksmith77 
1. Секретный ключ в порядке.
2. Не верно был настроен метод проверки. Надо ставить по домену, по остальным пока что особо не тестировалось.
3. Ключ повторно никак не сделать (это пока что). Можно давать тестовые копии только на localhost.
4. Это для удобства. Можно и не использовать.

**Comment by locksmith77** [comment]
Как давать тестовые копии на localhost?

**Comment by pafnuty** [comment]
@locksmith77 давать копию скрипта, но не давать ключ.

**Comment by locksmith77** [comment]
но по идее скрипт же не работает без ключа. какой смысл или я что-то не понимаю?

**Comment by Mofsy** [comment]
@locksmith77 use_localhost = true;

**Comment by locksmith77** [comment]
а вставлять после if($protect->status) {
    $license = true;
}
?

**Comment by locksmith77** [comment]
Если задать ключу имя и прописать в него юзера то ключ сначала активируется а потом начинает выдавать ошибку - Ошибка: локальный лицензионный ключ поврежден или не действителен.

**Comment by pafnuty** [comment]
@locksmith77 
А как вы сами думаете, куда вставлять? И что происходит при описанном условии?
Я не просто так спрашиваю, у  меня складывается ощущение, что вы слабо представляете, что делаете из-за слабого знания самого php, а скрипт рассчитан на людей, знающих php и способных написать и поддерживать свою разработку, куда внедряется клиентский класс.

**Comment by locksmith77** [comment]
я учусь:) и не стесняюсь об этом говорить. куда вставить представляю. просто вижу, что в скрипте не все работает и просто пытаюсь разобраться и помочь вам в отлове ошибок

**Comment by pafnuty** [comment]
> я учусь:) 
Тогда думаю вам следует изучит общие принципы ООП, и в частности могу порекомендовать статьи из серии (Объектно-ориентированный PHP)[http://ruseller.com/search.php?s=Объектно-ориентированный]. 
Одно дело учиться, а другое — задавать глупые вопросы.

**Comment by locksmith77** [comment]
это для вас они глупые...я дико извиняюсь если я надоел глупыми вопросами...
Ошибка: локальный лицензионный ключ поврежден или не действителен - начинает вылазить если прописать в ключе в имени пользователя больше одного слова.

**Comment by Mofsy** [comment]
@locksmith77 В этом то как раз ошибок нет. Есть только ваше недопонимание.
Как освобожусь от заказов, займусь доработкой панели для pcp-cs

**Comment by locksmith77** [comment]
Павел исправьте в статье орфографическую ошибку "локальный лицензионный ключ поврежден или не действителен" - недействителен пишется вместе

**Comment by Mofsy** [comment]
@locksmith77 недействительный билет - билет не действителен

**Comment by locksmith77** [comment]
не в данном контексте

**Comment by Mofsy** [comment]
@locksmith77 контекст не важен, это возможные варианты написания.

**Comment by locksmith77** [comment]
спасибо за ваш скрипт. желаю терпимости с такими как я:)
