### ISSUE TITLE
ппц

### ISSUE THREAD

**Issue by DeathStarName** [Mofsy/pcp-cs#19]
Убрать это и тому подобное и скрипт нуленный XDDDD

/ Если истина, то лицензия в боевом состоянии и можно работать дальше.
if($protect->status) {
    $license = true;
}

// Если есть ключ и задан ID новости и проверка лицензии прошла успешно — работаем
if ($cfg['newsId'] && $key && $license) {

**Comment by Mofsy** [comment]
Правда? А мы глупые такие и не знали про это.
