### ISSUE TITLE
Ошибка: локальный лицензионный ключ поврежден или не действителен.

### ISSUE THREAD

**Issue by CrazyTM** [Mofsy/pcp-cs#20]
Появляется данная ошибка, никак не исчезает, после долгих игр с методами и ключами.

**Ошибка: локальный лицензионный ключ поврежден или не действителен.**

1) Создал метод http://prntscr.com/iytxt4
2) Обмотал скрипт условием проверки

`
$ps = array();
$ps["licensy_key"] = 'F2B77-781CA-5C384-D726C-354F3';

// Клиентский класс -->
    
    class Protect{.....}

// Теперь можно запустить проверку лицензии
$protect = new Protect();

// Секретный ключ из созданного метода проверки
$protect->secret_key = 'cX0eHnP1GgvnuoHR2'; 

// Куда будем класть локальный (зашифрованный) ключ?
$protect->local_key_path = $_SERVER['DOCUMENT_ROOT'].'/';

// Имя и расширение локального ключа 
$protect->local_key_name = 'showattach.lic';

// Адрес сервера проверки
$protect->server = 'http://site.ru/api.php';

// Дата релиза модуля (пригодится если лицензия даётся на определённую версию модуля)
$protect->release_date = '';

// Ключ активации (лицензионный ключ), тот, который передаётся в параметрах строки подключения модуля
$protect->activation_key = $ps["licensy_key"];

// Сообщения о различных ошибках
$protect->status_messages = array(.....);

// Запускаем валидацию лицензии
$protect->validate();

$license = false;

// Если истина, то лицензия в боевом состоянии и можно работать дальше.
if($protect->status) {
    $license = true;
}

if ($ps["licensy_key"] && $license) {
    // ОСНОВНОЙ КОД САЙТА
}

if (!$ps["licensy_key"]) {
    // Если ключ не передан — надо бы сообщить об этом
    $showAttach = '<span style="color: red;">Не указан лицензионный ключ.</span>';
} 
if (!$license) {
    // Если лицензия не проверилась - скжем об этом
    $showAttach =  (!$protect->errors) ? 'Ошибка лицензии.' : $protect->errors;
}

echo $showAttach;
`

В общем по стандарту, создается ключ

YToxMzp7czo4OiJpbnN0YW5jZSI7YToxOntzOjY6ImRvbWFpbiI7YToyOntpOjA7
czoxOiJrIjtpOjE7czo1OiJ3d3cuayI7fX1zOjc6ImVuZm9yY2UiO2E6MTp7aTow
O3M6NjoiZG9tYWluIjt9czoxNToiZG9tYWluX3dpbGRjYXJkIjtzOjE6IjAiO3M6
NzoidXNlcl9pZCI7aTowO3M6OToidXNlcl9uYW1lIjtzOjA6IiI7czoxNDoiYWN0
aXZhdGlvbl9rZXkiO3M6Mjk6IkYyQjc3LTc4MUNBLTVDMzg0LUQ3MjZDLTM1NEYz
IjtzOjE1OiJsaWNlbnNlX3N0YXJ0ZWQiO2k6MTUyMjQ3OTM4MTtzOjIyOiJhY3Rp
dmF0aW9uX2tleV9leHBpcmVzIjtzOjEwOiIxNTIyNTMwMDAwIjtzOjE3OiJsb2Nh
bF9rZXlfZXhwaXJlcyI7aToxNTU0MDE1NDA3O3M6Njoic3RhdHVzIjtpOjE7czox
MzoiY3VzdG9tX2ZpZWxkcyI7YTowOnt9czoyMzoiZG93bmxvYWRfYWNjZXNzX2V4
cGlyZXMiO2k6MDtzOjIyOiJzdXBwb3J0X2FjY2Vzc19leHBpcmVzIjtpOjA7fXtw
cm90ZWN0fTZjMWVjYzM1Mzc2NzY3ZjBmNzY5ZDA2NDY2MDIzMTQxe3Byb3RlY3R9
ZmVhYWViMzUwMDQxNjc4NDA5YWUzOGIxNDI0NGEyY2I=

**Comment by Mofsy** [comment]
Здравствуйте, проект больше не поддерживается.
